# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/_objc-compat-import-private.h
src/_objc-compat-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/import-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/_objc-compat-import.h
src/_objc-compat-include.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/import.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/apple-alloca-glue.h
src/apple-isa-glue.h
src/apple-message-glue.h
src/apple-object-glue.h
src/apple-vararg-glue.h
src/mulle-alloca-glue.h
src/mulle-compiler-glue.h
src/mulle-isa-glue.h
src/mulle-message-glue.h
src/mulle-object-glue.h
src/mulle-vararg-glue.h
src/objc-compat.h
)

