/*
  This file will be regenerated by `mulle-sde update|monitor`.
  Edits will be lost.
  Suppress this file with MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE NONE|DISABLE.
*/

#ifndef _objc_compat_import_private_h__
#define _objc_compat_import_private_h__

/* no headers */

#endif
