#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
) 

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
src/apple-alloca-glue.h
src/apple-message-glue.h
src/apple-object-glue.h
src/apple-vararg-glue.h
src/import.h
src/include.h
src/mulle-alloca-glue.h
src/mulle-message-glue.h
src/mulle-object-glue.h
src/mulle-vararg-glue.h
src/objc-compat.h
) 

